# Generated by Django 4.2.2 on 2023-07-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_sets_set_rep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('workouts', models.ManyToManyField(to='main_app.workout')),
            ],
        ),
    ]
